### ISSUE TITLE
Event: Vim Pro

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#144]
# Vim Pro

> สอนใช้ vim ฟรีไม่มีค่าใช้จ่าย

กรุณากด Going ใน facebook ด้วยนะ :)

```
id: 'GeekyBaseVimPro20181007'
date: '2018-01-27'
time: '09:00 ~ 17:30'
location
  url: https://goo.gl/maps/Tv2WKsQGFVm
  title: Geeky Base
  detail: จอดรถฟรี
links:
 - type: RSVP
    url: https://www.facebook.com/events/335443820536158/
```
