### ISSUE TITLE
Post-event content?

### ISSUE THREAD

**Issue by unnawut** [ThaiProgrammer/tech-events-calendar#70]
For events that are already on the calendar, is it okay or recommended to update them with links to the content generated from the event?

E.g. links to the recorded livestreams, code repos, photo galleries, blog posts, etc.

This would make the calendar not useful just for future events but as an archive/reference for past events as well.

**Comment by dtinth** [comment]
Yes please! This is a great suggestion and a great way to make this project more useful. To do this, we need to figure out how to put these information in the markdown file.

Proposal: the `resources` key inside the front matter:

```yaml
resources:
  - type: video
    title: Recorded sessions
    url: https://www.youtube.com/playlist?list=PL37ZVnwpeshFqN5dcZ704lxI3F5iHDYkl
```

Type may be:

- `video`
- `code`
- `photo`
- `writeup`
- `slides`

Another question: What if there are community create resource about the content? e.g. someone (not the event organizer) wrote a blog post. How should we display it?
 One suggestion is to have another key, `community_resources` which is the same as `resources` but for content created by community.
